name: homecontrol
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  flutter_tflite: ^1.0.1
  get: ^4.6.6
  http: ^1.2.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:

    - assets/home.png
    - assets/suncloud.png
    - assets/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
          weight: 700
    - family: MotionControlNeueLite
      fonts:
        - asset: fonts/MotionControlNeueLite.otf
          weight: 700

